name: task-vectors
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - conda-forge::scs
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - cffi=1.15.1
  - cryptography
  - ffmpeg=4.3
  - freetype=2.10.4
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - jbig=2.1
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - lerc=2.2.1
  - libdeflate=1.7
  - libffi
  - libiconv=1.17
  - libpng=1.6.37
  - libtiff=4.3.0
  - libuuid=1.0.3
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - ncurses=6.3
  - nettle=3.6
  - numpy-base=1.23.1
  - openh264=2.1.1
  - openssl
  - pip=22.2.2
  - python=3.10
  - python_abi=3.10
  - pytorch=1.12.1
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2
  - setuptools=63.4.1
  - sqlite=3.39.3
  - tk=8.6.12
  - typing_extensions=4.3.0
  - tzdata=2022c
  - xz=5.2.6
  - zlib=1.2.12
  - zstd=1.5.0
  - pip:
    - certifi==2022.9.24
    - charset-normalizer==2.1.1
    - contourpy==1.0.5
    - cvxpy==1.2.2
    - cycler==0.11.0
    - ecos==2.0.10
    - filelock==3.8.0
    - fonttools==4.37.4
    - ftfy==6.1.1
    - huggingface-hub==0.10.0
    - idna==3.4
    - kiwisolver==1.4.4
    - matplotlib==3.6.0
    - numpy==1.23.3
    - open-clip-torch==2.0.2
    - osqp==0.6.2.post5
    - packaging==21.3
    - pandas==1.5.0
    - patsy==0.5.2
    - pillow==9.2.0
    - plotly==5.11.0
    - pycparser==2.21
    - pyopenssl==22.0.0
    - pyparsing==3.0.9
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - pytz==2022.4
    - pyyaml==6.0
    - qdldl==0.1.5.post2
    - regex==2022.9.13
    - requests==2.28.1
    - scipy==1.9.1
    - scs
    - seaborn==0.12.1
    - six==1.16.0
    - statsmodels==0.13.2
    - tenacity>=8.1.0
    - torch==1.12.1
    - torchaudio==0.12.1
    - torchvision==0.13.1
    - tqdm==4.64.1
    - typing-extensions==4.3.0
    - urllib3==1.26.12
    - wcwidth==0.2.5
    - wheel==0.37.1
